create database customer_churn

use customer_churn


select * from churn_modelling

-- wrute a query to calculate 
--		TOTAL NUMBER OF CUSTOMER
--		TOTAL CHURNED CUSTOMERS 
--		CHURN RATE %

SELECT 
	COUNT(*) AS TOTAL_CUSTOMERS,
	SUM(CASE WHEN Exited = 1 THEN 1 ELSE 0 END) AS TOTAL_CUSTOMER_CHURN,
	ROUND(100
	* SUM(CASE WHEN Exited = 1 THEN 1 ELSE 0 END) / COUNT(*),
		2) AS CHURN_PERCENTAGE
FROM Churn_Modelling

  

-- WRITE A QUERY TO CALCULATE CHURN RATE BY GENDER
--		GENDER
--		TOTAL CUSTOMER
--		TOTAL CHURNED
--		CHURN PERCENTAGE

SELECT 
	Gender,
	COUNT(*) AS TOTAL_CUSTOMER,
	SUM(CASE WHEN Exited = 1 THEN 1 ELSE 0 END) AS TOTAL_CHURNED,
	ROUND(
	100.0 * SUM(CASE WHEN Exited = 1 THEN 1 ELSE 0 END) / COUNT(*),2
	) AS CHURN_PERCENTAGE
FROM Churn_Modelling
GROUP BY Gender
  


-- WRITE A QUERY TO CALCULATE CHURN RATE BY GEOGRAPHY 
--		GEOGRAPHY
--		TOTAL CUSTOMER
--		TOTAL CHURNED
--		CHURN PERCENTAGE

SELECT 
	Geography,
	COUNT(*) AS TOTAL_CUSTOMERS,
	SUM(CASE WHEN Exited = 1 THEN 1 ELSE 0 END) AS TOTAL_CHURNED,
	ROUND(
		100.0 * SUM(CASE WHEN EXITED = 1 THEN 1 ELSE 0 END) / COUNT(*),
	2) AS CHURN_PERCENTAGE
FROM Churn_Modelling
GROUP BY Geography


  
-- WRITE A QUERY TO CALCULATE CHURN RATE BY AGE GROUP
--		AGE GROUP
--		TOTAL CUSTOMERS
--		TOTAL CHURNED
--		CHURN PERCENTAGE

SELECT 
	Age_Group,
	COUNT(*) AS TOTAL_CUSTOMERS,
	SUM(CASE WHEN EXITED = 1 THEN 1 ELSE 0 END) AS TOTAL_CHURNER,
	ROUND(
		100.0 * SUM(CASE WHEN EXITED = 1 THEN 1 ELSE 0 END) / COUNT(*),
	2) AS CHURN_PERCENTAGE
FROM Churn_Modelling
GROUP BY Age_Group

  

-- WRITE A QUERY TO SHOW 
--		AVERAGE BALANCE FOR CHURNED CUSTOMERS
--		AVERAGE BALANCE FOR NON CHURNED CUSTOMERS

SELECT 
	Exited,
	ROUND(AVG(BALANCE),2) AS AVERAGE_BALANCE
FROM Churn_Modelling
GROUP BY Exited
  


-- ARE HIGH BALANCE CUSTOMERS MORE LIKELY TO CHURN ?
-- WRITE A QUERY FOR CHURN RATE BY BALANCE CATEGORY
--		BALANCE CATEGORY
--		TOTAL CUSTOMERS
--		TOTAL CHURNED
--		CHURN %

SELECT 
	Balance_Category,
	COUNT(*) AS TOTAL_CUSTOMERS,
	SUM(CASE WHEN EXITED = 1 THEN 1 ELSE 0 END) AS TOTAL_CHURNED,
	ROUND(
		100.0 * SUM(CASE WHEN EXITED = 1 THEN 1 ELSE 0 END) / COUNT(*),
	2) AS CHURN_PERCENTAGE
FROM Churn_Modelling
GROUP BY Balance_Category


-- WRITE A QUERY TO FIND CHURN RATE BY AGE GROUP AND RISK LEVEL

SELECT 
	Age_Group,
	Risk_Level,
	COUNT(*) AS TOTAL_CUSTOMERS,
	SUM(CASE WHEN EXITED = 1 THEN 1 ELSE 0 END) AS TOTAL_CHURNED,
	ROUND(
		100.0 * SUM(CASE WHEN EXITED = 1 THEN 1 ELSE 0 END) / COUNT(*),
	2) AS CHURN_RATE
FROM Churn_Modelling
GROUP BY Age_Group,Risk_Level
ORDER BY Age_Group,CHURN_RATE DESC


-- WRITE A QUERY TO FIND 
/*		WHICH AGE GROUP CONTRIBUTES THE HIGHER NUMBER OF CHURNED CUSTOMERS (NOT PERCENTAGE
		ACTUAL VOLUME)*/

SELECT 
	Age_Group,
	SUM(CASE WHEN EXITED = 1 THEN 1 ELSE 0 END) AS CHURNED_CUSTOMERS
FROM Churn_Modelling
GROUP BY Age_Group
ORDER BY CHURNED_CUSTOMERS DESC
